[tool.black]

multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 88
exclude = '''
    /(
        \.git
        |\.hg
        |\.mypy_cache
        |\.tox
        |\.venv
        |_build
        |buck-out
        |build
        |dist
        |migrations,
        |__pycache__,
        |manage.py,
        |settings.py
    )/
'''